#!/bin/sh

# syslog
/sbin/syslogd -nO- &

# dovecot
sed -i -e '/^#disable_plaintext_auth =/a disable_plaintext_auth = no' /etc/dovecot/conf.d/10-auth.conf
sed -i -e '/^#auth_verbose =/a auth_verbose = yes' /etc/dovecot/conf.d/10-logging.conf
sed -i -e '/^#mail_location =/a mail_location = maildir:~/Maildir' /etc/dovecot/conf.d/10-mail.conf
sed -i -e 's/^ssl = required$/ssl = no/' /etc/dovecot/conf.d/10-ssl.conf

/usr/sbin/dovecot

# postfix + opendkim
[[ -z "${POSTFIX_MYHOSTNAME}" ]] && export POSTFIX_MYHOSTNAME="${HOSTNAME}"
cat <<EOT >>/etc/postfix/main.cf
smtp_tls_security_level = may
myhostname = ${POSTFIX_MYHOSTNAME}
mydestination = \$mydomain
home_mailbox = Maildir/
mailbox_command = /usr/sbin/procmail
EOT

[[ -n "${POSTFIX_MYNETWORKS}" ]] && {
  echo "mynetworks = 127.0.0.0/8 ${POSTFIX_MYNETWORKS}" >>/etc/postfix/main.cf
}

[[ -d '/etc/ssl/postfix' ]] && cat <<EOT >>/etc/postfix/main.cf
smtpd_tls_security_level = may
smtpd_use_tls = yes
smtpd_tls_cert_file = /etc/ssl/postfix/cert.pem
smtpd_tls_key_file = /etc/ssl/postfix/key.pem
EOT
[[ -d '/etc/ssl/postfix' ]] && sed -i \
  -e 's/^#\(submission\)/\1/' \
  -e 's/^#\(smtps\)/\1/' \
  -e 's/^#\(  -o syslog_name=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_security_level=\)/\1/' \
  -e 's/^#\(  -o smtpd_sasl_auth_enable=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_auth_only=\)/\1/' \
  -e 's/^#\(  -o smtpd_reject_unlisted_recipient=\)/\1/' \
  -e 's/^#\(  -o smtpd_recipient_restrictions=\)/\1/' \
  -e 's/^#\(  -o smtpd_relay_restrictions=\)/\1/' \
  -e 's/^#\(  -o milter_macro_daemon_name=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_wrappermode=\)/\1/' \
  /etc/postfix/master.cf

cat <<EOT >/etc/postfix/aliases
MAILER-DAEMON: postmaster
postmaster: root
abuse: root
EOT

(
  cd /home
  find . -maxdepth 1 | while read entry; do
    entry="${entry/\.\//}"
    [[ "$entry" == '.' || "$entry" == '..' ]] && continue
    case $(stat -c '%F' "$entry") in
    'directory')
      adduser -h /home/"$entry" -s /sbin/nologin -u "$(stat -c '%u' "$entry")" -G users -D "$entry"
      ;;
    'symbolic link')
      echo "${entry}: "$(readlink "${entry}") >> /etc/postfix/aliases
      ;;
    esac
  done
)

newaliases

[[ "${WITH_OPENDKIM}" == "true" ]] && {
  __domain=$(echo "${POSTFIX_MYHOSTNAME}" | sed -e 's/^[^.]*\.//')
  mkdir -p /run/opendkim
  sed -i -e "s/example.com/${__domain}/" /etc/opendkim/opendkim.conf
  echo "InternalHosts ${POSTFIX_MYNETWORKS}" >>/etc/opendkim/opendkim.conf
  (
    echo "smtpd_milters = inet:127.0.0.1:8891"
    echo "non_smtpd_milters = $smtpd_milters milter_default_action = accept"
  ) >>/etc/postfix/main.cf
}

[[ "${WITH_SPAMASSASSIN}" == "true" ]] && {
  /usr/bin/sa-update
  /usr/sbin/spamd --daemonize
}

/usr/sbin/opendkim
/usr/sbin/postfix start-fg
