#!/bin/sh

/sbin/syslogd -nO- &

[[ -z "${POSTFIX_MYHOSTNAME}" ]] && {
  echo "FATAL: environment variable POSTFIX_MYHOSTNAME is not set"
  exit 1
}

cat <<EOT >>/etc/postfix/main.cf
myhostname = ${POSTFIX_MYHOSTNAME}
mydestination = \$mydomain
home_mailbox = Maildir/
mailbox_command = /usr/sbin/procmail
EOT

[[ -n "${POSTFIX_MYNETWORKS}" ]] && {
  echo "mynetworks = 127.0.0.0/8 ${POSTFIX_MYNETWORKS}" >>/etc/postfix/main.cf
}

[[ -d '/etc/ssl/postfix' ]] && cat <<EOT >>/etc/postfix/main.cf
smtpd_tls_security_level = may
smtpd_use_tls = yes
smtpd_tls_cert_file = /etc/ssl/postfix/cert.pem
smtpd_tls_key_file = /etc/ssl/postfix/key.pem
EOT
[[ -d '/etc/ssl/postfix' ]] && sed -i \
  -e 's/^#\(  -o syslog_name=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_security_level=\)/\1/' \
  -e 's/^#\(  -o smtpd_sasl_auth_enable=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_auth_only=\)/\1/' \
  -e 's/^#\(  -o smtpd_reject_unlisted_recipient=\)/\1/' \
  -e 's/^#\(  -o smtpd_recipient_restrictions=\)/\1/' \
  -e 's/^#\(  -o smtpd_relay_restrictions=\)/\1/' \
  -e 's/^#\(  -o milter_macro_daemon_name=\)/\1/' \
  -e 's/^#\(  -o smtpd_tls_wrappermode=\)/\1/' \
  /etc/postfix/master.cf

cat <<EOT >/etc/postfix/aliases
MAILER-DAEMON: postmaster
postmaster: root
abuse: root
EOT

(
  cd /home
  find . -maxdepth 1 | while read entry; do
    entry="${entry/\.\//}"
    [[ "$entry" == '.' || "$entry" == '..' ]] && continue
    case $(stat -c '%F' "$entry") in
    'directory')
      adduser -h /home/"$entry" -s /sbin/nologin -u "$(stat -c '%u' "$entry")" -G users -D "$entry"
      ;;
    'symbolic link')
      echo "${entry}: "$(readlink "${entry}") >> /etc/postfix/aliases
      ;;
    esac
  done
)

newaliases

[[ "${WITH_OPENDKIM}" == "true" ]] && {
  __domain=$(echo "${POSTFIX_MYHOSTNAME}" | sed -e 's/^[^.]*\.//')
  mkdir -p /run/opendkim
  sed -i -e "s/example.com/${__domain}/" /etc/opendkim/opendkim.conf
  echo "InternalHosts ${POSTFIX_MYNETWORKS}" >>/etc/opendkim/opendkim.conf
  (
    echo "smtpd_milters = inet:127.0.0.1:8891"
    echo "non_smtpd_milters = $smtpd_milters milter_default_action = accept"
  ) >>/etc/postfix/main.cf
}

[[ "${WITH_SPAMASSASSIN}" == "true" ]] && {
  /usr/bin/sa-update
  /usr/sbin/spamd --daemonize
}

/usr/sbin/opendkim
/usr/sbin/postfix start-fg
